### ISSUE TITLE
SFTP connexion with non standard port ?

### ISSUE THREAD

**Issue by HB9HLI** [BlobBackup/BlobBackup#65]
Hello, 
The question is simple, how can i connect via sftp on non standard port ?
I have nothing found on docs.

Thanks for your help :-)

Dom.

**Comment by bimbashrestha** [comment]
This functionality isn't there yet. Although, I don't think it will be too hard to add since I'm using a sftp library that  I believe supports non standard ports.

I'm going to find some time this month to look at this and the other outstanding issues:)

**Comment by bimbashrestha** [comment]
Hey @HB9HL, so I looked into this again and it turns out the sftp library BlobBackup uses, `pysftp`, does not support non-standard ports. So I think adding this feature will likely mean having to use a new library and I'd prefer to not do that right now. Maybe if more people bring this up in the future, we can think about this again but for now, I think we'll have to wait on this feature. Sorry. 

Going to close the issue. Feel free to leave comments and reopen.
